on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  linkage-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install project to local Maven repository is done in entrypoint.sh
      #- run: ./gradlew build publishToMavenLocal -x test -x signMavenJavaPublication
      - uses: suztomo/cloud-opensource-java@v1

# Does this work?


