on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  linkage-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: mkdir -p /home/runner/work/_temp/_github_home
      # install project to local Maven repository
      - run: JAVA_OPTS="-Duser.home=/home/runner/work/_temp/_github_home" ./gradlew --debug build publishToMavenLocal -x test -x signMavenJavaPublication
      - run: find /home/runner/.m2 -name '*.pom'
      - run: find /home/runner/work/_temp/_github_home/.m2 -name '*.pom'
      # hard link cannot be used for directory
      # - run: ln -s /home/runner/.m2 /home/runner/work/_temp/_github_home/.m2
      - uses: suztomo/cloud-opensource-java@v1
