on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  linkage-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: java -version
      # install project to local Maven repository
      - run: ./gradlew build publishToMavenLocal -x test -x signMavenJavaPublication
      - uses: suztomo/cloud-opensource-java@v1

# Does this work


